### ISSUE TITLE
Default games config not under VC

### ISSUE THREAD

**Issue by ricardorzgz** [edouardkombo/laravel-slotmachine#1]
Default game.json is not provided when cloning the repository as content under app/storage is ignored in the gitignore file. At least one game.json sample needs to be provided to be used as an example on this test.

Thanks.

**Comment by edouardkombo** [comment]
A feature branch has been created, games.json is in the root folder ".games.json.example".

Readme.md has been updated as well.

Feature branch has been merged to master.

My apologies.
